### ISSUE TITLE
Vocabulary Class is referencing cakePHP v2 String class

### ISSUE THREAD

**Issue by paulrwest** [quickapps/website#6]
This was removed in v3 for PHP 7 support

To reproduce run PHP 7 and navigate to the URL /admin/taxonomy/vocabularies

> HP Fatal error:  Cannot use Cake\\Utility\\String as String because 'String' is a special class name in ....\\vendor\\quickapps-plugins\\taxonomy\\src\\Model\\Entity\\Vocabulary.php on line 15

Fix
line 15 replacing reference Cake\Utility\String to use Cake\Utility\Text;
line 36 Replace Class String to Text

**Comment by ChristopherCastro** [comment]
closing as it has been fixed.

Thanks for reporting!
